version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/budget_for_life
    ports:
      - "3000:3000"
    depends_on:
      - db
    env:
      - DB_HOST=db
  db:
    image: "postgres:latest"
    container_name: "bfl_postgres"
    ports:
      - "5432:5432"
    volumes:
      - bfl_dbdata:/var/lib/postgresql/data
volumes:
  bfl_dbdata:
